// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var arg, depFile, deps, fs, i, inFile, wrap, _i, _len, _ref;

  depFile = null;

  _ref = process.argv;
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    arg = _ref[i];
    if (arg === '--dep-file') {
      depFile = process.argv[i + 1];
      process.argv.splice(i, 2);
      break;
    }
  }

  inFile = null;

  deps = [];

  wrap = function(obj, fn) {
    var oldFn;
    oldFn = obj[fn];
    return obj[fn] = function(filename) {
      if (/\.(styl|css)$/.test(filename)) {
        if (inFile != null) {
          deps.push(filename);
        } else {
          inFile = filename;
        }
      }
      return oldFn.apply(this, arguments);
    };
  };

  fs = require('fs');

  wrap(fs, 'readFile');

  wrap(fs, 'readFileSync');

  require('stylus/bin/stylus');

  process.on('exit', function() {
    var depString;
    depString = "" + inFile + ": " + (deps.join(' '));
    if (depFile != null) {
      return fs.writeFileSync(depFile, depString);
    } else {
      return process.stdout.write(depString);
    }
  });

}).call(this);

//# sourceMappingURL=stylus-dep.map
