// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var crypto, fs;

  fs = require('fs');

  crypto = require('crypto');

  exports.computeDigest = function(sourcePath, callback) {
    var shasum, stream;
    shasum = crypto.createHash('md5');
    stream = fs.ReadStream(sourcePath);
    stream.on('error', function(error) {
      return callback(error);
    });
    stream.on('data', function(data) {
      return shasum.update(data);
    });
    return stream.on('end', function() {
      var digest;
      digest = shasum.digest('hex').substr(0, 8);
      return callback(null, digest);
    });
  };

}).call(this);

//# sourceMappingURL=utils.map
